---
title: The Good Side
timezone: UTC
collections:
  case-studies:
    title: Case Studies
    output: true
  home-carousel:
    title: Home Carousel
    output: true
  navigation:
    title: Navigation
    output: false
  posts:
    title: Posts
    output: true
  questions:
    title: Questions
    output: true
  themes:
    title: Themes
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: questions
  values:
    Case Study Link: 
- scope:
    path: case-studies
  values:
    Case study main image: 
    Case study top image: 
    Case study title: 
    Question: 
    Blocks:
    - Image: 
      Article text: 
      Video: 
      Testimonial: 
      Carousel:
      - Image: 
    Meta:
    - Related links: 
      Where we worked: 
      The Network: 
      Methods: 
      Tags: 
      Data: 
      Video: 
      Hashtag: 
email: your-email@example.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: 
url: 
twitter_username: jekyllrb
github_username: jekyll
theme: minima
sass:
  sass_dir: "./_scss"
plugins:
- jekyll-feed
